blog/urls.py
from django.urls import path
from blog.views import *
from .feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>/', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:username>/',blog_view, name='author'),
    path('search/',blog_search,name='search'),
    path("rss/feed/", LatestEntriesFeed()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.conf.urls import handler404


sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('portfolio/', include('portfolio.urls')),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.handler404'

website/urls.py
from django.urls import path
from website.views import *
app_name = 'website'

urlpatterns = [
    path('', home, name='home'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('services', services, name='services'),
    path('newsletter', newsletter, name='newsletter'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    name=models.CharField(max_length=31)
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    # author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)  # Add author as a foreign key
    author = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    counted_comment = models.IntegerField(default=0)
    category=models.ManyToManyField(Category)
    image = models.ImageField(upload_to='post_images/') 
    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return "{}-{}".format(self.title, self.id)
    
    def get_absolute_url(self):
        # Replace 'your_model_detail_url_name' with the name of the URL pattern
        # you've defined in your project's URL configuration for this model's detail view.
        return reverse('blog:single',kwargs={'pid': self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField() 
    subject = models.CharField(max_length=200)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} - {self.subject}'

blog/forms.py
from django import forms
from .models import Comment  # Import the Comment model from your models.py

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment  # Specify the model to use for the form
        fields = ['name', 'email', 'subject', 'message']  # Define the fields to include in the for

blog/views.py
from django.shortcuts import render
from .models import Post,Comment
from .forms import CommentForm
from django.shortcuts import render, get_object_or_404,redirect
from django.utils import timezone
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.urls import reverse 
from django.http import QueryDict




def blog_view(request, **kwargs):
    current_time = timezone.now()
    posts = Post.objects.filter(status=True, published_date__lte=current_time).order_by('-published_date')
    if kwargs.get('cat_name'):
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('username'):
        posts = posts.filter(author__username=kwargs['username'])

    if kwargs.get('tag_name'):
        posts = posts.filter(tags__name=kwargs['tag_name'])
    # Fetch tags for each post and include them in the context

    for post in posts:
        post.tags = post.tags.all()

    paginator = Paginator(posts, 3)

    try:
        page_number = request.GET.get('page')
        posts = paginator.get_page(page_number)
    except EmptyPage:
        posts = paginator.get_page(1)
    except PageNotAnInteger:
        posts = paginator.get_page(1)

    context = {'posts': posts,}
    return render(request, 'blog/blog-home.html', context)

def blog_single(request, pid):
    current_time = timezone.now()
    post = get_object_or_404(Post, pk=pid, status=True, published_date__lte=current_time)
    all_posts = Post.objects.filter(status=True, published_date__lte=current_time).order_by('-published_date')
    comments = Comment.objects.filter(post=post, approved=True).order_by('-created_date')
    current_index = list(all_posts).index(post)
    next_post = all_posts[current_index - 1] if current_index > 0 else None
    previous_post = all_posts[current_index + 1] if current_index < len(all_posts) - 1 else None
    post.counted_views += 1
    post.save()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        
        if request.user.is_authenticated:
            initial_data = {
                'name': request.user.username,
                'email': request.user.email,
            }
            combined_data = {**initial_data, **request.POST}
            comment_form = CommentForm(combined_data)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            messages.success(request, 'Submitted correctly')
            return redirect(request.path_info)
        else:
            messages.error(request, 'Oops, there was an error in the form submission!') 
    else:
        comment_form = CommentForm()

    return render(request, 'blog/blog-single.html', {
        'post': post,
        'previous_post': previous_post,
        'next_post': next_post,
        'comments': comments,
        'comment_form': comment_form,
    })

def blog_search(request):
    query = request.GET.get('s')  # Retrieve the 's' parameter from the GET request
    posts = Post.objects.filter(status=1)

    if query:
        # Use 'icontains' for case-insensitive search in both title and content
        posts = posts.filter(title__icontains=query) | posts.filter(content__icontains=query)

    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

templates/blog/blog-comments.html
{% load static %}
{% load humanize %}

<div class="comment__wrap">
    <div class="comment__title">
        <h4 class="title">({{ comments|length }}) Comments</h4>
    </div>
    <ul class="comment__list">
        {% for comment in comments %}
        <li class="comment__item">
            <div class="comment__thumb">
                <img src="{% static 'img/blog/c1.jpg' %}" alt="">
            </div>
            <div class="comment__content">
                <div class="comment__avatar__info">
                    <div class="info">
                        <h4 class="title">{{ comment.name }}</h4>
                        <span class="date">{{ comment.created_date|naturalday }}</span>
                    </div>
                </div>
                <p>{{ comment.message }}</p>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="comment__form">
    <div class="comment__title">
        <h4 class="title">Leave a Comment</h4>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ comment_form.errors }}
        
        {% if not request.user.is_authenticated %}
        <div class="row">
            <div class="col-md-6">
                <input type="text" name="name" placeholder="Enter your name*" required>
            </div>
            <div class="col-md-6">
                <input type="email" name="email" placeholder="Enter your mail*" required>
            </div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col-md-6">
                <input type="text" name="subject" placeholder="Subject" required>
            </div>
            <div class="col-md-6">
                <input type="text" placeholder="Website*">
            </div>
        </div>
        <textarea name="message" placeholder="Enter your Message*" required></textarea>

        <button type="submit" class="btn">Post Comment</button>
    </form>
</div>

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %} 
        <!-- main-area -->
        <main>

            <!-- breadcrumb-area -->
            <section class="breadcrumb__wrap">
                <div class="container custom-container">
                    <div class="row justify-content-center">
                        <div class="col-xl-6 col-lg-8 col-md-10">
                            <div class="breadcrumb__wrap__content">
                                <h2 class="title">Recent Article</h2>
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="{% url 'website:home' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Blog</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="breadcrumb__wrap__icon">
                    <ul>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon01.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon02.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon03.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon04.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon05.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon06.png' %}" alt=""></li>
                    </ul>
                </div>
            </section>
            <!-- breadcrumb-area-end -->


            <!-- blog-area -->
            <section class="standard__blog">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8">
                            <!-- _____________________________________________________________ -->
                            {% for post in posts %}
                            <div class="standard__blog__post">
                                <div class="standard__blog__thumb">
                                    <a href="{% url 'blog:single' pid=post.id %}"><img src="{{ post.image.url }}" alt="{{ post.title }}"></a>
                                    <a href="{% url 'blog:single' pid=post.id %}" class="blog__link"><i class="far fa-long-arrow-right"></i></a>
                                </div>
                                <div class="standard__blog__content">
                                    <div class="blog__post__avatar">
                                        <div class="thumb"><img src="{% static 'assets/img/blog/blog_avatar.png' %}" alt=""></div>
                                        <span class="post__by">By : <a href="#">{{post.author}}</a></span>
                                    </div>
                                    <h2 class="title"><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></h2>
                                    <p>{{ post.content|truncatewords_html:45|safe }}</p>
                                    <ul class="blog__post__meta">
                                        <li><i class="fal fa-calendar-alt"></i>{{post.published_date|date:"D M Y"}}</li>
                                        <li><i class="fal fa-comments-alt"></i> Comment ({% comment_count post.id%})</li>
                                        <li><i class=""></i> Views (<b>{{post.counted_views}}</b>)</li>
                                    </ul>
                                </div>
                            </div>
                            {% endfor %}
                            <!-- _____________________________________________________________ -->
                            <div class="pagination-wrap">
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination">
                                        <li class="page-item">
                                            {% if posts.has_previous %}
                                                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                                                    <i class="far fa-long-arrow-left"></i>
                                                </a>
                                            {% else %}
                                                <span class="page-link" aria-hidden="true">
                                                    <i class="far fa-long-arrow-left"></i>
                                                </span>
                                            {% endif %}
                                        </li>
                                        {% for page in posts.paginator.page_range %}
                                            <li class="page-item{% if page == posts.number %} active{% endif %}">
                                                <a href="?page={{ page }}" class="page-link">{{ page }}</a>
                                            </li>
                                        {% endfor %}
                                        <li class="page-item">
                                            {% if posts.has_next %}
                                                <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                                                    <i class="far fa-long-arrow-right"></i>
                                                </a>
                                            {% else %}
                                                <span class="page-link" aria-hidden="true">
                                                    <i class="far fa-long-arrow-right"></i>
                                                </span>
                                            {% endif %}
                                        </li>
                                    </ul>
                                </nav>
                            </div>  
                            <br> <br> <br><br><br><br>

                            
                        </div>
                        <div class="col-lg-4">
                            <aside class="blog__sidebar">
                            {% include 'blog/blog-search.html' %}
                            {% popularposts %}
                            {% postcategories %}
                            {% include 'blog/blog-recent-comment.html' %}
                            {% posttags %}
                            {% include 'blog/blog-newsletter.html' %}

                            </aside>
                        </div>
                    </div>
                </div>
            </section>
            <!-- blog-area-end -->


            <!-- contact-area -->
            {% include 'website/index-contact.html' %}
            <!-- contact-area-end -->

        </main>
        <!-- main-area-end -->
{% endblock content %}

templates/blog/blog-newsletter.html
{% load static %}

<div class="single-sidebar-widget newsletter-widget">
    <h4 class="newsletter-title">Newsletter</h4>
    <div class="form-group d-flex flex-row">
        <div class="col-autos">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </div>
                </div>
                <form action="{% url 'website:newsletter' %}" method="post" >
                    {% csrf_token %}    
                <input
                    type="email"
                    name="email"
                    class="form-control"
                    id="inlineFormInputGroup"
                    placeholder="Enter email"
                    onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter email'"
                />
            </div>
        </div>
            <button type="submit" class="">Subscribe</button>
         </form>
    </div>
    <p class="text-bottom">You can unsubscribe at any time</p>
</div>

templates/blog/blog-post-categories.html
<div class="widget">
    <h4 class="widget-title">Categories</h4>
    <ul class="sidebar__cat">
        {% for name, count in categories.items %}
        <li class="sidebar__cat__item">
            <a href="{% url 'blog:category' cat_name=name %}">
                {{ name }} ({{ count }})
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-recent-comment.html
<!-- <div class="widget">
    <h4 class="widget-title">Recent Comment</h4>
    <ul class="sidebar__comment">
        <li class="sidebar__comment__item">
            <a href="blog-details.html">Rasalina Sponde</a>
            <p>There are many variations of passages of lorem ipsum available, but the majority have</p>
        </li>
        <li class="sidebar__comment__item">
            <a href="blog-details.html">Rasalina Sponde</a>
            <p>There are many variations of passages of lorem ipsum available, but the majority have</p>
        </li>
        <li class="sidebar__comment__item">
            <a href="blog-details.html">Rasalina Sponde</a>
            <p>There are many variations of passages of lorem ipsum available, but the majority have</p>
        </li>
        <li class="sidebar__comment__item">
            <a href="blog-details.html">Rasalina Sponde</a>
            <p>There are many variations of passages of lorem ipsum available, but the majority have</p>
        </li>
    </ul>
</div> -->

templates/blog/blog-recent-posts.html
{% load static %}
{% load humanize %}

<div class="widget">
    <h4 class="widget-title">Recent Blog</h4>
    <ul class="rc__post">
        {% for post in posts %}
        <li class="rc__post__item">
            <div class="rc__post__thumb">
                <a href="{% url 'blog:single' pid=post.id %}">
                    <img class="img-fluid" src="{{ post.image.url }}" alt="">
                </a>
            </div>
            <div class="rc__post__content">
                <h5 class="title">
                    <a href="{% url 'blog:single' pid=post.id %}">{{ post.title }}</a>
                </h5>
                <span class="post-date"><i class="fal fa-calendar-alt"></i> {{ post.published_date|naturaltime }}</span>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-search.html
<div class="widget">
    <form action="{% url 'blog:search' %}" class="search-form">
        <input placeholder="Search" name="s"
        type="text"
        onfocus="this.placeholder = ''"
        onblur="this.placeholder = 'Search Posts'">
        <button type="submit"><i class="fal fa-search"></i></button>
    </form>
</div>

templates/blog/blog-single.html
{% extends 'base.html' %} 
{% load static %}
{% load blog_tags %}
{% block content %} 
        <!-- main-area -->
        <main>

            <!-- breadcrumb-area -->
            <section class="breadcrumb__wrap">
                <div class="container custom-container">
                    <div class="row justify-content-center">
                        <div class="col-xl-6 col-lg-8 col-md-10">
                            <div class="breadcrumb__wrap__content">
                                <h2 class="title">{{post.title}}</h2>   
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="{% url 'website:home' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Blog Details</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="breadcrumb__wrap__icon">
                    <ul>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon01.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon02.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon03.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon04.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon05.png' %}" alt=""></li>
                        <li><img src="{% static 'assets/img/icons/breadcrumb_icon06.png' %}" alt=""></li>
                    </ul>
                </div>
            </section>
            <!-- breadcrumb-area-end -->


            <!-- blog-details-area -->
            <section class="standard__blog blog__details">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="standard__blog__post">
                                <div class="standard__blog__thumb">
                                    <img src="{{ post.image.url }}" alt="{{ post.title }}">
                                </div>
                                <div class="blog__details__content services__details__content">
                                    <ul class="blog__post__meta">
                                        <li><i class="fal fa-calendar-alt"></i>{{post.published_date|date:"D M Y"}}</li>
                                        <li><i class="fal fa-comments-alt"></i> Comment ({% comment_count post.id%})</li>
                                        <li><i class=""></i> Views (<b>{{post.counted_views}}</b>)</li>
                                    </ul>
                                    <h2 class="title">{{post.title}}</h2>
                                    <p>{{post.content|safe}}</p>
                                </div>
                                <div class="blog__details__bottom">
                                    <ul class="blog__details__tag">
                                        <li class="title">Tag:</li>
                                        {% for tag in post.tags.all %}
                                        <li class="tags-list">
                                            <a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a>
                                            {% endfor %}
                                        </li>
                                    </ul>
                                    <ul class="blog__details__social">
                                        <li class="title">Share :</li>
                                        <li class="social-icons">
                                            <a href="#"><i class="fab fa-facebook"></i></a>
                                            <a href="#"><i class="fab fa-twitter-square"></i></a>
                                            <a href="#"><i class="fab fa-linkedin"></i></a>
                                            <a href="#"><i class="fab fa-pinterest"></i></a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="blog__next__prev">
                                    <div class="row justify-content-between">
                                        <div class="col-xl-5 col-md-6">
                                            <div class="blog__next__prev__item">
                                                <h4 class="title">{% if previous_post %}<a href="{% url 'blog:single' previous_post.pk %}">Previous Post</a>{% else %}No previous post{% endif %}</h4>
                                                {% if previous_post %}
                                                <div class="blog__next__prev__post">
                                                    <div class="blog__next__prev__thumb">
                                                        <a href="{% url 'blog:single' previous_post.pk %}">
                                                            <img class="img-fluid" src="{{ previous_post.image.url }}" alt="">
                                                        </a>
                                                    </div>
                                                    <div class="blog__next__prev__content">
                                                        <h5 class="title">
                                                            <a href="{% url 'blog:single' previous_post.pk %}">{{ previous_post.title }}</a>
                                                        </h5>
                                                    </div>
                                                </div>
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div class="col-xl-5 col-md-6">
                                            <div class="blog__next__prev__item next_post text-end">
                                                <h4 class="title">{% if next_post %}<a href="{% url 'blog:single' next_post.pk %}">Next Post</a>{% else %}No next post{% endif %}</h4>
                                                {% if next_post %}
                                                <div class="blog__next__prev__post">
                                                    <div class="blog__next__prev__thumb">
                                                        <a href="{% url 'blog:single' next_post.pk %}">
                                                            <img class="img-fluid" src="{{ next_post.image.url }}" alt="">
                                                        </a>
                                                    </div>
                                                    <div class="blog__next__prev__content">
                                                        <h5 class="title">
                                                            <a href="{% url 'blog:single' next_post.pk %}">{{ next_post.title }}</a>
                                                        </h5>
                                                    </div>
                                                </div>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- comment -->
                                {% include 'blog/blog-comments.html' %}
                                <!-- end comment -->
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <aside class="blog__sidebar">
                                {% include 'blog/blog-search.html' %}
                                {% popularposts %}
                                {% postcategories %}
                                {% include 'blog/blog-recent-comment.html' %}
                                {% posttags %}
                                {% include 'blog/blog-newsletter.html' %}

                            </aside>
                        </div>
                    </div>
                </div>
            </section>
            <!-- blog-details-area-end -->


            <!-- contact-area -->
            {% include 'website/index-contact.html' %}
            <!-- contact-area-end -->

        </main>
        <!-- main-area-end -->
        {% endblock content %}

templates/blog/blog-tags.html
<!-- Existing code -->
<div class="widget">
    <h4 class="widget-title">Tags</h4>
    <ul class="sidebar__tags">
        {% for tag in tags %}
            <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>
</div>