accounts/urls.py
# accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
    path('password_reset/', views.custom_password_reset, name='password_reset'),
    path('accounts/password_reset/confirm/<uidb64>/<token>/', views.custom_password_reset_confirm, name='custom_password_reset_confirm'),
]

blog/urls.py
from django.urls import path
from blog.views import *
from .feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>/', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:username>/',blog_view, name='author'),
    path('search/',blog_search,name='search'),
    path("rss/feed/", LatestEntriesFeed()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.conf.urls import handler404


sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('portfolio/', include('portfolio.urls')),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.handler404'

portfolio/urls.py
from django.urls import path
from .views import *

app_name = 'portfolio'

urlpatterns = [
    path('',portfolio, name='index'),
    path('details/',portfolio, name='details'),
]

website/urls.py
from django.urls import path
from website.views import *
app_name = 'website'

urlpatterns = [
    path('', home, name='home'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('services', services, name='services'),
    path('newsletter', newsletter, name='newsletter'),
]

templates/base.html
{% load static %}
{% load compress %}

<!doctype html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Rasalina - Personal Portfolio HTML Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">
        <!-- Place favicon.ico in the root directory -->

		<!-- CSS here -->
        {% compress css %}
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/default.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
        {% endcompress %}
    </head>
    <body>

        <!-- preloader-start -->
        <div id="preloader">
            <div class="rasalina-spin-box"></div>
        </div>
        <!-- preloader-end -->

		<!-- Scroll-top -->
        <button class="scroll-top scroll-to-target" data-target="html">
            <i class="fas fa-angle-up"></i>
        </button>
        <!-- Scroll-top-end-->

        <!-- header-area -->
        <header>
            <div id="sticky-header" class="menu__area transparent-header">
                <div class="container custom-container">
                    <div class="row">
                        <div class="col-12">
                            <div class="mobile__nav__toggler"><i class="fas fa-bars"></i></div>
                            <div class="menu__wrap">
                                <nav class="menu__nav">
                                    <div class="logo">
                                        <a href="{% url 'website:home' %}" class="logo__black"><img src="{% static 'assets/img/logo/logo_black.png' %}" alt=""></a>
                                        <a href="{% url 'website:home' %}" class="logo__white"><img src="{% static 'assets/img/logo/logo_white.png' %}" alt=""></a>
                                    </div>
                                    <div class="navbar__wrap main__menu d-none d-xl-flex">
                                        <ul class="navigation">
                                            <li class="active"><a href="{% url 'website:home' %}">Home</a></li>
                                            <li><a href="{% url 'website:about' %}">About</a></li>
                                            <li><a href="{% url 'website:services' %}">Services</a></li>
                                            <li class="menu-item-has-children"><a href="{% url 'portfolio:index' %}">Portfolio</a>
                                                <ul class="sub-menu">
                                                    <li><a href="{% url 'portfolio:index' %}">Portfolio</a></li>
                                                    <li><a href="{% url 'portfolio:details' %}">Portfolio Details</a></li>
                                                </ul>
                                            </li>
                                            <li class="menu-item-has-children"><a href="{% url 'blog:index' %}">Our Blog</a>
                                            </li>
                                            <li><a href="{% url 'website:contact' %}">contact me</a></li>
                                        </ul>
                                    </div>
                                    <div class="header__btn d-none d-md-block">
                                            <ul>
                                                {% if user.is_authenticated %}
                                                    <li><a href="{% url 'accounts:logout' %}" class="btn">Logout</a></li>
                                                {% else %}
                                                    <li><a href="{% url 'accounts:login' %}" class="btn">Login</a></li>
                                                {% endif %}
                                            </ul>
                                    </div>
                                </nav>
                            </div>
                            <!-- Mobile Menu  -->
                            <div class="mobile__menu">
                                <nav class="menu__box">
                                    <div class="close__btn"><i class="fal fa-times"></i></div>
                                    <div class="nav-logo">
                                        <a href="{% url 'website:home' %}" class="logo__black"><img src="{% static 'assets/img/logo/logo_black.png' %}" alt=""></a>
                                        <a href="{% url 'website:home' %}" class="logo__white"><img src="{% static 'assets/img/logo/logo_white.png' %}" alt=""></a>
                                    </div>
                                    <div class="menu__outer">
                                        <!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header-->
                                    </div>
                                    <div class="social-links">
                                        <ul class="clearfix">
                                            <li><a href="#"><span class="fab fa-twitter"></span></a></li>
                                            <li><a href="#"><span class="fab fa-facebook-square"></span></a></li>
                                            <li><a href="#"><span class="fab fa-pinterest-p"></span></a></li>
                                            <li><a href="#"><span class="fab fa-instagram"></span></a></li>
                                            <li><a href="#"><span class="fab fa-youtube"></span></a></li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                            <div class="menu__backdrop"></div>
                            <!-- End Mobile Menu -->
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- header-area-end -->

        <!-- main-area -->
        {% include 'website/messages.html' %}

        {% block content %} 
        {% endblock content %}
        <!-- main-area-end -->



        <!-- Footer-area -->
        <footer class="footer">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-lg-4">
                        <div class="footer__widget">
                            <div class="fw-title">
                                <h5 class="sub-title">Contact us</h5>
                                <h4 class="title">+81383 766 284</h4>
                            </div>
                            <div class="footer__widget__text">
                                <p>There are many variations of passages of lorem ipsum
                                available but the majority have suffered alteration
                                in some form is also here.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-6">
                        <div class="footer__widget">
                            <div class="fw-title">
                                <h5 class="sub-title">my address</h5>
                                <h4 class="title">AUSTRALIA</h4>
                            </div>
                            <div class="footer__widget__address">
                                <p>Level 13, 2 Elizabeth Steereyt set <br> Melbourne, Victoria 3000</p>
                                <a href="mailto:noreply@envato.com" class="mail">noreply@envato.com</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-sm-6">
                        <div class="footer__widget">
                            <div class="fw-title">
                                <h5 class="sub-title">Follow me</h5>
                                <h4 class="title">socially connect</h4>
                            </div>
                            <div class="footer__widget__social">
                                <p>Lorem ipsum dolor sit amet enim. <br> Etiam ullamcorper.</p>
                                <ul class="footer__social__list">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fab fa-behance"></i></a></li>
                                    <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="copyright__wrap">
                    <div class="row">
                        <div class="col-12">
                            <div class="copyright__text text-center">
                                <p>Copyright @ Theme_Pure 2021 All right Reserved</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer-area-end -->




		<!-- JS here -->
        {% compress js %}
        <script src="{% static 'assets/js/vendor/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'assets/js/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'assets/js/element-in-view.js' %}"></script>
        <script src="{% static 'assets/js/slick.min.js' %}"></script>
        <script src="{% static 'assets/js/ajax-form.js' %}"></script>
        <script src="{% static 'assets/js/wow.min.js' %}"></script>
        <script src="{% static 'assets/js/plugins.js' %}"></script>
        <script src="{% static 'assets/js/main.js' %}"></script>
        {% endcompress %}
    </body>
</html>